### ISSUE TITLE
Move to autogenerated promo_proto.rs

### ISSUE THREAD

**Issue by overvenus** [posix4e/rust-metrics#51]
Hello @posix4e 

Do you have any plan when `promo_proto.rs` will be added?

I found rust-metrics can not be compile even after disabled `prometheus`, cargo reports `error: file not found for module 'promo_proto'`

Here is my Cargo.toml

``` toml
[dependencies.metrics]
git = "https://github.com/posix4e/rust-metrics.git"
```

I dont want use v0.1.1 in crate.io, because master branch has changed many place, and it breaks v0.1.1 API.

I can send a PR to fix this issue if you want.
